version: "3"
services:

  # Container do apache
  veus-apache:
    image: veus-apache
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: veus-apache
    volumes:
      - ./:/var/www/html/
    expose:
      - 80
    depends_on:
      - "veus-mysql"
    networks:
      - rede-veus
    env_file:
      - ./.env

  # Container do nginx
  veus-nginx:
    image: nginx:1.17.0
    container_name: veus-nginx
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - rede-veus
    volumes:
      - ./docker/nginx-gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "veus-apache"

  # Container do mysql
  veus-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: veus-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      # Le o password direto do .env
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - rede-veus

networks:
  rede-veus:
    driver: bridge
