version: "3"
services:

  # Container do apache
  veus-apache:
    image: veus-apache
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: veus-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - "veus-mysql"
    networks:
      - rede-veus
    env_file:
      - ./.env

  # Container do mysql
  veus-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: veus-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      # Le o password direto do .env
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - rede-veus

networks:
  rede-veus:
    driver: bridge
